const ADD_ENTRY = 'ADD_ENTRY';
const EDIT_ENTRY = 'EDIT_ENTRY';
const DELETE_ENTRY = 'DELETE_ENTRY';
const CLEAR_CURRENT_ENTRY = 'CLEAR_CURRENT_ENTRY';
const SET_CURRENT_ENTRY = 'SET_CURRENT_ENTRY';

const Constants = {
  ADD_ENTRY,
  EDIT_ENTRY,
  DELETE_ENTRY,
  SET_CURRENT_ENTRY,
  CLEAR_CURRENT_ENTRY,
};

export default Constants;


